"""
PDF generation for Nagarik Sahayak eligibility reports.
Uses fpdf2 with Noto Sans (English) + Noto Sans Devanagari (Hindi).
"""
from fpdf import FPDF
from pathlib import Path
from datetime import datetime, timezone

FONTS_DIR = Path(__file__).parent / "fonts"


def generate_eligibility_pdf(
    profile: dict,
    eligibility_results: list,
    scheme_detail: dict = None,
    output_path: str = "/tmp/report.pdf",
) -> str:
    """
    Generate a clean eligibility report PDF.

    Args:
        profile: {name, age, income, state}
        eligibility_results: list of {scheme, scheme_hi, eligible, reason, benefit}
        scheme_detail: optional single-scheme detail dict for focused report
        output_path: where to save the PDF

    Returns:
        path to generated PDF
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Register fonts
    pdf.add_font("NS", "", str(FONTS_DIR / "NotoSans-Regular.ttf"))
    pdf.add_font("NS", "B", str(FONTS_DIR / "NotoSans-Bold.ttf"))
    pdf.add_font("NH", "", str(FONTS_DIR / "NotoSansDevanagari-Regular.ttf"))

    pdf.add_page()

    # === HEADER BAR ===
    pdf.set_fill_color(255, 153, 51)  # Saffron
    pdf.rect(0, 0, 210, 18, "F")
    pdf.set_fill_color(19, 136, 8)  # India Green
    pdf.rect(0, 18, 210, 2, "F")

    pdf.set_y(4)
    pdf.set_font("NS", "B", 16)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "Nagarik Sahayak", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(22)
    pdf.set_font("NH", size=12)
    pdf.set_text_color(0, 0, 128)  # Navy
    pdf.cell(0, 8, "ELIGIBILITY REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

    # Reference & date
    ref_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    pdf.set_font("NS", size=8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Ref: NS-{ref_id}  |  Date: {datetime.now(timezone.utc).strftime('%d %b %Y, %H:%M UTC')}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # === PROFILE SECTION ===
    _section_header(pdf, "Applicant Profile")

    name = profile.get("name", "N/A")
    age = profile.get("age", "N/A")
    income = profile.get("income", 0)
    state = profile.get("state", "N/A")
    income_str = f"Rs {income:,}/month" if isinstance(income, (int, float)) and income > 0 else "N/A"

    _profile_row(pdf, "Name", str(name))
    _profile_row(pdf, "Age", f"{age} years")
    _profile_row(pdf, "Monthly Income", income_str)
    _profile_row(pdf, "State", str(state))

    pdf.ln(4)

    # === ELIGIBILITY RESULTS ===
    _section_header(pdf, "Scheme Eligibility Assessment")

    for r in eligibility_results:
        _eligibility_block(pdf, r)

    pdf.ln(4)

    # === SINGLE SCHEME DETAIL (optional) ===
    if scheme_detail:
        _section_header(pdf, f"Scheme Details: {scheme_detail.get('title', '')}")
        pdf.set_font("NS", size=9)
        pdf.set_text_color(60, 60, 60)

        desc = scheme_detail.get("description", "")
        if desc:
            pdf.multi_cell(0, 5, f"Description: {desc}")
            pdf.ln(2)

        elig = scheme_detail.get("eligibility", "")
        if elig:
            pdf.multi_cell(0, 5, f"Eligibility Criteria: {elig}")
            pdf.ln(2)

        benefits = scheme_detail.get("benefits", "")
        if benefits:
            pdf.multi_cell(0, 5, f"Benefits: {benefits}")
            pdf.ln(2)

        pdf_url = scheme_detail.get("pdf_url", "")
        if pdf_url:
            pdf.set_text_color(0, 0, 128)
            pdf.multi_cell(0, 5, f"Official Guidelines: {pdf_url}")
            pdf.set_text_color(60, 60, 60)

        pdf.ln(4)

    # === FOOTER ===
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("NS", size=7)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, (
        "Disclaimer: This is an automated eligibility assessment based on the information provided. "
        "Final eligibility is subject to verification by the respective government authority. "
        "Please visit your nearest Common Service Centre (CSC) or the official scheme website for application.\n"
        "Generated by Nagarik Sahayak | Digital India Initiative"
    ), align="C")

    pdf.output(output_path)
    return output_path


def _section_header(pdf: FPDF, title: str):
    pdf.set_fill_color(240, 240, 248)
    pdf.set_draw_color(0, 0, 128)
    pdf.set_font("NS", "B", 11)
    pdf.set_text_color(0, 0, 128)
    pdf.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT", border="B")
    pdf.ln(3)


def _profile_row(pdf: FPDF, label: str, value: str):
    pdf.set_font("NS", "B", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(45, 6, label)
    pdf.set_font("NS", size=9)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")


def _eligibility_block(pdf: FPDF, result: dict):
    eligible = result.get("eligible", False)
    scheme = result.get("scheme", "")
    reason = result.get("reason", "")
    benefit = result.get("benefit", "")

    # Background color
    if eligible:
        pdf.set_fill_color(240, 253, 244)  # green-50
        pdf.set_draw_color(34, 197, 94)
        status_text = "ELIGIBLE"
        status_color = (22, 163, 74)
    else:
        pdf.set_fill_color(254, 242, 242)  # red-50
        pdf.set_draw_color(239, 68, 68)
        status_text = "NOT ELIGIBLE"
        status_color = (220, 38, 38)

    y_start = pdf.get_y()
    pdf.rect(10, y_start, 190, 22, "DF")

    # Scheme name
    pdf.set_xy(14, y_start + 2)
    pdf.set_font("NS", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(130, 6, scheme)

    # Status badge
    pdf.set_font("NS", "B", 8)
    pdf.set_text_color(*status_color)
    pdf.cell(0, 6, status_text, align="R")

    # Reason
    pdf.set_xy(14, y_start + 9)
    pdf.set_font("NS", size=8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, reason[:120], new_x="LMARGIN", new_y="NEXT")

    # Benefit (if eligible)
    if eligible and benefit:
        pdf.set_xy(14, y_start + 15)
        pdf.set_font("NS", size=8)
        pdf.set_text_color(22, 163, 74)
        pdf.cell(0, 5, f"Benefit: {benefit}")

    pdf.set_y(y_start + 25)
