"""
Tests for the PDF form filler module.

Covers:
- AcroForm filling (fillable PDFs)
- Text overlay filling (non-fillable PDFs)
- Unified fill_pdf_form entry point
- Field value formatting (no masking for official forms)
- Field name normalization and fuzzy matching
- Error handling for missing files/libraries
- PDF generator is_draft parameter
"""
import os
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

# Check if PyMuPDF is available
try:
    import fitz
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False


# ─── Helper: create test PDFs ───

def _create_text_pdf(text: str = "Name: ________") -> str:
    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    for line in text.split("\n"):
        pdf.cell(0, 10, text=line, new_x="LMARGIN", new_y="NEXT")
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    pdf.output(tmp.name)
    return tmp.name


# ─── Value formatting ───

class TestValueFormatting:
    def test_aadhaar_is_masked_even_on_an_official_form(self):
        """This used to assert the opposite, and the assertion was the bug.

        The printed form asks for all twelve digits, so writing all twelve felt
        like the helpful thing to do. But Aadhaar Act s29(4) makes publishing
        an Aadhaar number an offence, and this file is generated by the
        application, stored encrypted, and downloaded — putting the number
        somewhere the citizen no longer controls. The last four identify the
        record; the eight the citizen writes by hand on the counter copy are
        theirs to write.
        """
        from pdf_filler import _format_value_for_fill

        result = _format_value_for_fill("123456789012", "aadhaar")
        assert result != "123456789012"
        assert "9012" in result
        assert "12345678" not in result

    def test_a_filled_form_never_carries_twelve_digits(self):
        from dpdp.aadhaar_policy import contains_full_aadhaar
        from pdf_filler import _format_value_for_fill

        written = _format_value_for_fill("234567890124", "aadhaar")
        assert not contains_full_aadhaar({"written_to_pdf": written})

    def test_masking_survives_separators_the_citizen_typed(self):
        from pdf_filler import _format_value_for_fill

        for typed in ("2345 6789 0124", "2345-6789-0124", "234567890124"):
            assert "0124" in _format_value_for_fill(typed, "aadhaar")
            assert "23456789" not in _format_value_for_fill(typed, "aadhaar")

    def test_format_phone_10_digits(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("9876543210", "phone")
        assert result == "9876543210"

    def test_format_phone_with_country_code(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("919876543210", "phone")
        assert result == "9876543210"

    def test_format_date_iso(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("1990-05-15", "date")
        assert result == "15/05/1990"

    def test_format_empty_value(self):
        from pdf_filler import _format_value_for_fill
        assert _format_value_for_fill("", "text") == ""
        assert _format_value_for_fill(None, "text") == ""

    def test_format_text_passthrough(self):
        from pdf_filler import _format_value_for_fill
        assert _format_value_for_fill("Raj Kumar", "text") == "Raj Kumar"


# ─── Field name normalization ───

class TestFieldNameNormalization:
    def test_normalize_simple(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("applicant_name") == "applicant_name"

    def test_normalize_with_brackets(self):
        from pdf_filler import _normalize_field_name
        result = _normalize_field_name("form[0].applicant_name")
        assert result == "form_0_applicant_name"

    def test_normalize_with_spaces(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("Applicant Name") == "applicant_name"

    def test_normalize_with_dots(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("field.name.here") == "field_name_here"

    def test_normalize_uppercase(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("MOBILE_NUMBER") == "mobile_number"


# ─── AcroForm filling ───

class TestAcroFormFilling:
    def test_fill_nonexistent_file(self):
        from pdf_filler import fill_acroform_pdf
        result = fill_acroform_pdf("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    def test_fill_non_fillable_pdf(self):
        from pdf_filler import fill_acroform_pdf
        if not HAS_FITZ:
            # Without fitz, should return "not available"
            result = fill_acroform_pdf("/any.pdf", "/tmp/out.pdf", {"name": "Test"})
            assert result["success"] is False
            return

        pdf_path = _create_text_pdf("Just plain text")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            result = fill_acroform_pdf(pdf_path, out_path, {"name": "Test"})
            assert result["success"] is False
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_fill_acroform_pdf(self):
        """Test filling a real AcroForm PDF."""
        doc = fitz.open()
        page = doc.new_page()
        widget = fitz.Widget()
        widget.field_type = fitz.PDF_WIDGET_TYPE_TEXT
        widget.field_name = "applicant_name"
        widget.rect = fitz.Rect(100, 100, 300, 120)
        widget.field_value = ""
        page.add_widget(widget)
        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
        doc.save(tmp.name)
        doc.close()
        pdf_path = tmp.name

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            from pdf_filler import fill_acroform_pdf
            result = fill_acroform_pdf(
                pdf_path, out_path,
                field_values={"applicant_name": "Raj Kumar"},
            )
            assert result["success"] is True
            assert result["filled_count"] == 1
            assert result["method"] == "acroform"
            assert os.path.exists(out_path)
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_fill_when_fitz_unavailable(self):
        from pdf_filler import fill_acroform_pdf
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_acroform_pdf("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            assert "not available" in result["error"]


# ─── Text overlay filling ───

class TestOverlayFilling:
    def test_overlay_nonexistent_file(self):
        from pdf_filler import fill_overlay_pdf
        result = fill_overlay_pdf("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_overlay_with_manual_positions(self):
        from pdf_filler import fill_overlay_pdf
        pdf_path = _create_text_pdf("Name: ________\nPhone: ________")
        out_path = tempfile.mktemp(suffix=".pdf")
        positions = [
            {"profileKey": "name", "page": 1, "x": 100, "y": 100, "font_size": 10},
            {"profileKey": "phone", "page": 1, "x": 100, "y": 130, "font_size": 10},
        ]
        try:
            result = fill_overlay_pdf(
                pdf_path, out_path,
                field_values={"name": "Test User", "phone": "9876543210"},
                field_positions=positions,
            )
            assert result["success"] is True
            assert result["filled_count"] == 2
            assert result["method"] == "overlay"
            assert os.path.exists(out_path)
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_overlay_auto_detect_no_positions(self):
        from pdf_filler import fill_overlay_pdf
        if not HAS_FITZ:
            result = fill_overlay_pdf("/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            return
        pdf_path = _create_text_pdf("Some text")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            result = fill_overlay_pdf(
                pdf_path, out_path,
                field_values={"name": "Test"},
            )
            assert result["method"] == "overlay"
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_overlay_when_fitz_unavailable(self):
        from pdf_filler import fill_overlay_pdf
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_overlay_pdf("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False


# ─── Unified fill_pdf_form ───

class TestUnifiedFiller:
    def test_fill_pdf_form_nonexistent(self):
        from pdf_filler import fill_pdf_form
        result = fill_pdf_form("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_fill_pdf_form_with_overlay_positions(self):
        """Unified filler should fall back to overlay when no AcroForm fields."""
        pdf_path = _create_text_pdf("Name: ________")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            from pdf_filler import fill_pdf_form
            result = fill_pdf_form(
                pdf_path, out_path,
                field_values={"name": "Test"},
                field_positions=[{"profileKey": "name", "page": 1, "x": 100, "y": 100, "font_size": 10}],
            )
            assert result["success"] is True
            assert result["method"] == "overlay"
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_fill_pdf_form_when_fitz_unavailable(self):
        from pdf_filler import fill_pdf_form
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_pdf_form("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            assert result["method"] == "none"


# ─── PDF generator is_draft parameter ───

class TestPdfGeneratorDraft:
    def test_format_field_value_draft_masks_aadhaar(self):
        from pdf_generator import _format_field_value
        result = _format_field_value("123456789012", "aadhaar", is_draft=True)
        assert "XXXX" in result
        assert "123456789012" not in result

    def test_final_output_also_masks_aadhaar(self):
        """Even a non-draft form must not carry the number (s29(4))."""
        from pdf_generator import _format_field_value
        result = _format_field_value("123456789012", "aadhaar", is_draft=False)
        assert result == "XXXX XXXX 9012"
        assert "12345678" not in result

    def test_aadhaar_is_masked_regardless_of_the_full_flag(self):
        """Aadhaar Act s29(4) forbids displaying the number.

        These PDFs are written to disk and shared, and UIDAI permits only the
        masked form, so the unmasked branch was removed. `full` is still
        accepted for signature compatibility but is deliberately ignored —
        honouring it would leave a criminal exposure one keyword argument away.
        The citizen writes the full number onto the printed form themselves.
        """
        from pdf_generator import _mask_aadhaar
        assert _mask_aadhaar("123456789012", full=True) == "XXXX XXXX 9012"
        assert _mask_aadhaar("123456789012", full=False) == "XXXX XXXX 9012"

    def test_generate_pdf_with_draft_false_no_watermark(self):
        """Generating with is_draft=False should produce a valid PDF."""
        from pdf_generator import generate_real_filled_form_pdf

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            generate_real_filled_form_pdf(
                filled_fields={"name": "Test User"},
                scheme_name="Test Scheme",
                form_fields=[{"fieldName": "name", "profileKey": "name", "labelEnglish": "Name",
                              "labelHindi": "naam", "type": "text", "required": True, "section": "Details"}],
                sections=[{"name": "Details", "nameHindi": "vivaran"}],
                output_path=out_path,
                is_draft=False,
            )
            assert os.path.exists(out_path)
            assert os.path.getsize(out_path) > 0
        finally:
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_generate_pdf_with_draft_true(self):
        """Generating with is_draft=True should produce a valid PDF."""
        from pdf_generator import generate_real_filled_form_pdf

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            generate_real_filled_form_pdf(
                filled_fields={"name": "Test User"},
                scheme_name="Test Scheme",
                form_fields=[{"fieldName": "name", "profileKey": "name", "labelEnglish": "Name",
                              "labelHindi": "naam", "type": "text", "required": True, "section": "Details"}],
                sections=[{"name": "Details", "nameHindi": "vivaran"}],
                output_path=out_path,
                is_draft=True,
            )
            assert os.path.exists(out_path)
            assert os.path.getsize(out_path) > 0
        finally:
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_format_field_value_empty(self):
        from pdf_generator import _format_field_value
        assert _format_field_value(None) == "_______________"
        assert _format_field_value("") == "_______________"

    def test_format_field_value_date(self):
        from pdf_generator import _format_field_value
        assert _format_field_value("1990-05-15", "date") == "15/05/1990"

    def test_format_field_value_phone(self):
        from pdf_generator import _format_field_value
        result = _format_field_value("9876543210", "phone")
        assert "98765" in result


# ─── Placing values on a real printed form ───

class TestLabelMatching:
    """Government forms print their own words, not the app's.

    The catalog calls a field "Full Name (as per Aadhaar)". The Haryana sports
    scholarship form calls it "Name of the Applicant". Matching only on the
    catalog label left the single most important field on the page blank.
    """

    def test_the_form_s_own_phrasing_is_recognised(self):
        from pdf_filler import FIELD_ALIASES

        assert "name of the applicant" in FIELD_ALIASES["name"]
        assert "bank's name" in FIELD_ALIASES["bank_name"]
        assert "aadhar no" in FIELD_ALIASES["aadhaar_number"], \
            "forms spell it Aadhar as often as Aadhaar"

    def test_relations_are_listed_before_the_bare_name(self):
        """"father's name" and "name" both match "Father's Name:". Resolving to
        the shorter one writes the applicant's own name onto their father's
        line, which is worse than leaving it blank."""
        from pdf_filler import _alias_hit

        hit = _alias_hit("4. father's name:", "father_husband_name", ())
        assert hit == "father's name"

    def test_search_handles_the_apostrophes_a_scan_produces(self):
        """OCR emits a typographic apostrophe, so a literal search finds
        nothing on a page that plainly reads Mother's Name."""
        from pdf_filler import _search_variants

        variants = _search_variants("mother's name")
        assert "mother’s name" in variants
        assert "mothers name" in variants


class TestProseIsRefused:
    """A label match inside a printed paragraph writes a value into the middle
    of a legal undertaking."""

    def test_a_declaration_sentence_is_not_a_label(self):
        from pdf_filler import _looks_like_a_label

        prose = ("Self-attested copy of my sports achievements, date of birth, "
                 "Bank Pass Book, Domicile Certificate have been enclosed.")
        assert not _looks_like_a_label(prose)

    @pytest.mark.parametrize("label", [
        "1. District:", "b) Sex: Male/Female", "Bank's Name:",
        "IFSC Code: --ll.", "9. Aadhar No:",
    ])
    def test_real_labels_are_accepted(self, label):
        """"IFSC Code: --ll." is a good label followed by scan noise. An
        earlier heuristic rejected anything ending in a full stop and threw it
        away."""
        from pdf_filler import _looks_like_a_label

        assert _looks_like_a_label(label)

    def test_a_long_line_is_not_a_label(self):
        from pdf_filler import _looks_like_a_label, MAX_LABEL_CHARS

        assert not _looks_like_a_label("x" * (MAX_LABEL_CHARS + 1))


class TestUnplacedIsReported:
    """A printed form rarely has a labelled box for every field the catalog
    knows. Saying which ones are missing is the difference between a citizen
    completing the form at home and finding out at the counter."""

    FIELDS = [
        {"profileKey": "name", "labelEnglish": "Full Name",
         "labelHindi": "पूरा नाम", "required": True},
        {"profileKey": "pincode", "labelEnglish": "PIN Code",
         "labelHindi": "पिन कोड", "required": True},
        {"profileKey": "branch_name", "labelEnglish": "Branch Name",
         "labelHindi": "शाखा", "required": False},
    ]

    def test_supplied_but_unplaceable_values_are_listed(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report(
            positions=[{"profileKey": "name"}],
            field_values={"name": "Priya", "pincode": "124507",
                          "branch_name": "Main"},
            form_fields=self.FIELDS,
        )
        keys = {r["profileKey"] for r in report}
        assert keys == {"pincode", "branch_name"}

    def test_the_report_says_which_ones_are_mandatory(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report(
            [], {"pincode": "124507", "branch_name": "Main"}, self.FIELDS)
        by_key = {r["profileKey"]: r for r in report}
        assert by_key["pincode"]["required"] is True
        assert by_key["branch_name"]["required"] is False

    def test_the_reason_is_bilingual(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report([], {"pincode": "124507"}, self.FIELDS)
        assert report[0]["reason"] and report[0]["reasonHindi"]
        assert report[0]["labelHindi"]

    def test_a_value_the_citizen_never_gave_is_not_reported(self):
        """They are not told to hand-write something they never supplied."""
        from pdf_filler import _unplaced_report

        # Only `name` was supplied, and it was placed. PIN code and branch are
        # unplaceable but blank, so there is nothing to warn about.
        assert _unplaced_report(
            [{"profileKey": "name"}], {"name": "Priya"}, self.FIELDS) == []

    def test_the_overlay_result_carries_the_shortfall(self):
        from pdf_filler import _unplaced_report
        import inspect
        import pdf_filler

        source = inspect.getsource(pdf_filler.fill_overlay_pdf)
        assert '"unplaced": _unplaced_report(' in source, \
            "a shortfall computed and not returned is a shortfall not reported"
        assert callable(_unplaced_report)


# ─── OCR-tolerant label matching ───

class TestOcrTolerance:
    """Real scans mangle labels in ways invisible until you print the text.

    The Haryana form carries "Mother's·Name:" — a middle dot where the space
    should be, making it a single token — and "Name ofTournament" with the
    space missing. Both are perfectly legible on the page and neither is
    findable with an exact search.
    """

    def test_normalisation_strips_what_ocr_invents(self):
        from pdf_filler import _normalise_token

        assert _normalise_token("Mother's·Name:") == "mothersname"
        assert _normalise_token("Aadhar  No.") == "aadharno"

    def test_close_words_score_high_and_distant_ones_low(self):
        from pdf_filler import _token_ratio

        assert _token_ratio("institution", "institution") == 1.0
        assert _token_ratio("mothersname", "fathersname") < 0.86
        assert _token_ratio("mother", "brother") < 0.86

    def test_father_and_mother_can_never_trade_places(self):
        """The near-miss that put the mother's name on the father's row.
        They differ by two characters in eleven and score 0.82, so the floor
        sits above that — and the first character must survive as well, because
        anything that changes who a value refers to is worse than no match."""
        from pdf_filler import OCR_TOKEN_SIMILARITY, _token_ratio

        assert _token_ratio("fathersname", "mothersname") < OCR_TOKEN_SIMILARITY

    def test_a_stray_ocr_letter_does_not_make_a_label_into_prose(self):
        """This form yields "I Mother's Occupation:". Matching " i " in a
        23-character label threw the field away."""
        from pdf_filler import _looks_like_a_label

        assert _looks_like_a_label("I Mother's Occupation: ")
        assert not _looks_like_a_label(
            "It is certified that I have not applied for sports scholarship "
            "from SAI or Central Govt.")


class TestPreFlightAudit:
    """What the form asks for, checked before anything is written to it."""

    FIXTURE = "/tmp/demo_fill/original.pdf"

    @pytest.fixture
    def scheme(self):
        from data.gov_forms import get_by_name
        return get_by_name("Sports Achievement Scholarship (Haryana)")

    @pytest.fixture
    def audit(self, scheme):
        import os
        pytest.importorskip("numpy")
        if not os.path.exists(self.FIXTURE):
            pytest.skip("run scripts/demo_fill.py to fetch the source form")
        from pdf_filler import audit_form
        return audit_form(self.FIXTURE, scheme["extractedFields"], {})

    def test_the_grid_is_read_before_writing(self, audit):
        assert audit["available"] and audit["gridDetected"]

    def test_it_reports_which_fields_the_form_can_take(self, audit):
        assert audit["addressableOnForm"]
        assert "name" in audit["addressableOnForm"]

    def test_it_reports_which_fields_the_form_cannot_take(self, audit):
        """A field with no labelled slot comes out blank. Naming it is the
        difference between a citizen completing the form at home and finding
        out at the counter."""
        assert "pincode" in audit["notAddressableOnForm"]

    def test_a_missing_pdf_degrades_instead_of_raising(self, scheme):
        from pdf_filler import audit_form

        result = audit_form("/nonexistent.pdf", scheme["extractedFields"], {})
        assert result["available"] is False and result["error"]

    def test_the_catalog_now_models_what_the_form_asks(self, scheme):
        """Father's Occupation, Mother's Occupation and Parivar Pehchan Patra
        are printed on this form. The catalog had no fields for them, so they
        came out blank on every application and nothing reported it — there was
        no field to be missing. The audit found them."""
        keys = {f["profileKey"] for f in scheme["extractedFields"]}
        assert {"father_occupation", "mother_occupation",
                "state_family_id"} <= keys


class TestPostFillVerification:
    """Placement is computed from the unfilled page, so nothing is certain
    until the file exists and is read back."""

    def test_two_values_on_one_line_are_reported(self):
        from pdf_filler import _collides

        a = {"x": 100, "y": 200, "width": 60, "font_size": 10}
        b = {"x": 130, "y": 200, "width": 60, "font_size": 10}
        assert _collides(a, b)

    def test_adjacent_table_rows_are_not_a_collision(self):
        """Rows on this form sit 13 points apart with 9.7-point text. A glyph
        box a full font-height tall made every vertical neighbour look like a
        clash, and Mother's Name was refused because Father's Name was above."""
        from pdf_filler import _collides

        a = {"x": 100, "y": 181.5, "width": 67, "font_size": 9.7}
        b = {"x": 100, "y": 168.5, "width": 64, "font_size": 9.7}
        assert not _collides(a, b)

    def test_values_side_by_side_do_not_collide(self):
        from pdf_filler import _collides

        a = {"x": 100, "y": 200, "width": 40, "font_size": 10}
        b = {"x": 200, "y": 200, "width": 40, "font_size": 10}
        assert not _collides(a, b)

    def test_a_missing_output_file_degrades(self):
        from pdf_filler import verify_filled_pdf

        result = verify_filled_pdf("/nonexistent.pdf", [])
        assert result["verified"] is False

    def test_a_real_fill_comes_back_clean(self):
        import os
        pytest.importorskip("numpy")
        if not os.path.exists("/tmp/demo_fill/original.pdf"):
            pytest.skip("run scripts/demo_fill.py to fetch the source form")

        import tempfile
        from data.gov_forms import get_by_name
        from pdf_filler import fill_pdf_form
        from validation import verhoeff_check_digit

        scheme = get_by_name("Sports Achievement Scholarship (Haryana)")
        profile = {
            "name": "Priya Sharma", "father_husband_name": "Rajesh Sharma",
            "mother_name": "Kamla Sharma",
            "father_occupation": "Farmer", "mother_occupation": "Homemaker",
            "aadhaar_number": "73629184057" + verhoeff_check_digit("73629184057"),
            "date_of_birth": "2005-08-14", "gender": "Female", "category": "OBC",
            "mobile_number": "9812345678", "email": "priya@example.com",
            "address_line": "House No. 214, Sector 7", "district": "Jhajjar",
            "state": "Haryana", "pincode": "124507",
            "institution_name": "Government College for Women",
            "sport_name": "Kabaddi",
            "bank_account_number": "39281746503921",
            "ifsc_code": "PUNB0123456", "bank_name": "Punjab National Bank",
        }
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            out = tmp.name
        report = fill_pdf_form("/tmp/demo_fill/original.pdf", out, profile,
                               scheme["extractedFields"])
        os.unlink(out)

        assert report["success"]
        check = report["verification"]
        assert check["verified"]
        assert check["clean"], check["problems"]
        assert check["checked"] == report["filled_count"]

    def test_the_written_record_carries_the_final_text(self):
        """Font size and text both change during writing — shrink to fit, then
        truncation — so the check must see the final state, not the plan."""
        import os
        pytest.importorskip("numpy")
        if not os.path.exists("/tmp/demo_fill/original.pdf"):
            pytest.skip("run scripts/demo_fill.py to fetch the source form")

        import tempfile
        from data.gov_forms import get_by_name
        from pdf_filler import fill_pdf_form

        scheme = get_by_name("Sports Achievement Scholarship (Haryana)")
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            out = tmp.name
        report = fill_pdf_form("/tmp/demo_fill/original.pdf", out,
                               {"name": "Priya Sharma"},
                               scheme["extractedFields"])
        os.unlink(out)

        assert report["written"]
        entry = report["written"][0]
        assert {"profileKey", "page", "x", "y", "width",
                "font_size", "text"} <= set(entry)
        assert entry["text"] == "Priya Sharma"
