"""
Tests for the PDF form filler module.

Covers:
- AcroForm filling (fillable PDFs)
- Text overlay filling (non-fillable PDFs)
- Unified fill_pdf_form entry point
- Field value formatting (no masking for official forms)
- Field name normalization and fuzzy matching
- Error handling for missing files/libraries
- PDF generator is_draft parameter
"""
import os
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

# Check if PyMuPDF is available
try:
    import fitz
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False


# ─── Helper: create test PDFs ───

def _create_text_pdf(text: str = "Name: ________") -> str:
    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    for line in text.split("\n"):
        pdf.cell(0, 10, text=line, new_x="LMARGIN", new_y="NEXT")
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    pdf.output(tmp.name)
    return tmp.name


# ─── Value formatting ───

class TestValueFormatting:
    def test_aadhaar_is_masked_even_on_an_official_form(self):
        """This used to assert the opposite, and the assertion was the bug.

        The printed form asks for all twelve digits, so writing all twelve felt
        like the helpful thing to do. But Aadhaar Act s29(4) makes publishing
        an Aadhaar number an offence, and this file is generated by the
        application, stored encrypted, and downloaded — putting the number
        somewhere the citizen no longer controls. The last four identify the
        record; the eight the citizen writes by hand on the counter copy are
        theirs to write.
        """
        from pdf_filler import _format_value_for_fill

        result = _format_value_for_fill("123456789012", "aadhaar")
        assert result != "123456789012"
        assert "9012" in result
        assert "12345678" not in result

    def test_a_filled_form_never_carries_twelve_digits(self):
        from dpdp.aadhaar_policy import contains_full_aadhaar
        from pdf_filler import _format_value_for_fill

        written = _format_value_for_fill("234567890124", "aadhaar")
        assert not contains_full_aadhaar({"written_to_pdf": written})

    def test_masking_survives_separators_the_citizen_typed(self):
        from pdf_filler import _format_value_for_fill

        for typed in ("2345 6789 0124", "2345-6789-0124", "234567890124"):
            assert "0124" in _format_value_for_fill(typed, "aadhaar")
            assert "23456789" not in _format_value_for_fill(typed, "aadhaar")

    def test_format_phone_10_digits(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("9876543210", "phone")
        assert result == "9876543210"

    def test_format_phone_with_country_code(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("919876543210", "phone")
        assert result == "9876543210"

    def test_format_date_iso(self):
        from pdf_filler import _format_value_for_fill
        result = _format_value_for_fill("1990-05-15", "date")
        assert result == "15/05/1990"

    def test_format_empty_value(self):
        from pdf_filler import _format_value_for_fill
        assert _format_value_for_fill("", "text") == ""
        assert _format_value_for_fill(None, "text") == ""

    def test_format_text_passthrough(self):
        from pdf_filler import _format_value_for_fill
        assert _format_value_for_fill("Raj Kumar", "text") == "Raj Kumar"


# ─── Field name normalization ───

class TestFieldNameNormalization:
    def test_normalize_simple(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("applicant_name") == "applicant_name"

    def test_normalize_with_brackets(self):
        from pdf_filler import _normalize_field_name
        result = _normalize_field_name("form[0].applicant_name")
        assert result == "form_0_applicant_name"

    def test_normalize_with_spaces(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("Applicant Name") == "applicant_name"

    def test_normalize_with_dots(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("field.name.here") == "field_name_here"

    def test_normalize_uppercase(self):
        from pdf_filler import _normalize_field_name
        assert _normalize_field_name("MOBILE_NUMBER") == "mobile_number"


# ─── AcroForm filling ───

class TestAcroFormFilling:
    def test_fill_nonexistent_file(self):
        from pdf_filler import fill_acroform_pdf
        result = fill_acroform_pdf("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    def test_fill_non_fillable_pdf(self):
        from pdf_filler import fill_acroform_pdf
        if not HAS_FITZ:
            # Without fitz, should return "not available"
            result = fill_acroform_pdf("/any.pdf", "/tmp/out.pdf", {"name": "Test"})
            assert result["success"] is False
            return

        pdf_path = _create_text_pdf("Just plain text")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            result = fill_acroform_pdf(pdf_path, out_path, {"name": "Test"})
            assert result["success"] is False
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_fill_acroform_pdf(self):
        """Test filling a real AcroForm PDF."""
        doc = fitz.open()
        page = doc.new_page()
        widget = fitz.Widget()
        widget.field_type = fitz.PDF_WIDGET_TYPE_TEXT
        widget.field_name = "applicant_name"
        widget.rect = fitz.Rect(100, 100, 300, 120)
        widget.field_value = ""
        page.add_widget(widget)
        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
        doc.save(tmp.name)
        doc.close()
        pdf_path = tmp.name

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            from pdf_filler import fill_acroform_pdf
            result = fill_acroform_pdf(
                pdf_path, out_path,
                field_values={"applicant_name": "Raj Kumar"},
            )
            assert result["success"] is True
            assert result["filled_count"] == 1
            assert result["method"] == "acroform"
            assert os.path.exists(out_path)
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_fill_when_fitz_unavailable(self):
        from pdf_filler import fill_acroform_pdf
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_acroform_pdf("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            assert "not available" in result["error"]


# ─── Text overlay filling ───

class TestOverlayFilling:
    def test_overlay_nonexistent_file(self):
        from pdf_filler import fill_overlay_pdf
        result = fill_overlay_pdf("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_overlay_with_manual_positions(self):
        from pdf_filler import fill_overlay_pdf
        pdf_path = _create_text_pdf("Name: ________\nPhone: ________")
        out_path = tempfile.mktemp(suffix=".pdf")
        positions = [
            {"profileKey": "name", "page": 1, "x": 100, "y": 100, "font_size": 10},
            {"profileKey": "phone", "page": 1, "x": 100, "y": 130, "font_size": 10},
        ]
        try:
            result = fill_overlay_pdf(
                pdf_path, out_path,
                field_values={"name": "Test User", "phone": "9876543210"},
                field_positions=positions,
            )
            assert result["success"] is True
            assert result["filled_count"] == 2
            assert result["method"] == "overlay"
            assert os.path.exists(out_path)
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_overlay_auto_detect_no_positions(self):
        from pdf_filler import fill_overlay_pdf
        if not HAS_FITZ:
            result = fill_overlay_pdf("/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            return
        pdf_path = _create_text_pdf("Some text")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            result = fill_overlay_pdf(
                pdf_path, out_path,
                field_values={"name": "Test"},
            )
            assert result["method"] == "overlay"
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_overlay_when_fitz_unavailable(self):
        from pdf_filler import fill_overlay_pdf
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_overlay_pdf("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False


# ─── Unified fill_pdf_form ───

class TestUnifiedFiller:
    def test_fill_pdf_form_nonexistent(self):
        from pdf_filler import fill_pdf_form
        result = fill_pdf_form("/tmp/nonexistent.pdf", "/tmp/out.pdf", {})
        assert result["success"] is False

    @pytest.mark.skipif(not HAS_FITZ, reason="PyMuPDF not installed")
    def test_fill_pdf_form_with_overlay_positions(self):
        """Unified filler should fall back to overlay when no AcroForm fields."""
        pdf_path = _create_text_pdf("Name: ________")
        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            from pdf_filler import fill_pdf_form
            result = fill_pdf_form(
                pdf_path, out_path,
                field_values={"name": "Test"},
                field_positions=[{"profileKey": "name", "page": 1, "x": 100, "y": 100, "font_size": 10}],
            )
            assert result["success"] is True
            assert result["method"] == "overlay"
        finally:
            os.unlink(pdf_path)
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_fill_pdf_form_when_fitz_unavailable(self):
        from pdf_filler import fill_pdf_form
        with patch("pdf_filler._HAS_FITZ", False):
            result = fill_pdf_form("/tmp/any.pdf", "/tmp/out.pdf", {})
            assert result["success"] is False
            assert result["method"] == "none"


# ─── PDF generator is_draft parameter ───

class TestPdfGeneratorDraft:
    def test_format_field_value_draft_masks_aadhaar(self):
        from pdf_generator import _format_field_value
        result = _format_field_value("123456789012", "aadhaar", is_draft=True)
        assert "XXXX" in result
        assert "123456789012" not in result

    def test_final_output_also_masks_aadhaar(self):
        """Even a non-draft form must not carry the number (s29(4))."""
        from pdf_generator import _format_field_value
        result = _format_field_value("123456789012", "aadhaar", is_draft=False)
        assert result == "XXXX XXXX 9012"
        assert "12345678" not in result

    def test_aadhaar_is_masked_regardless_of_the_full_flag(self):
        """Aadhaar Act s29(4) forbids displaying the number.

        These PDFs are written to disk and shared, and UIDAI permits only the
        masked form, so the unmasked branch was removed. `full` is still
        accepted for signature compatibility but is deliberately ignored —
        honouring it would leave a criminal exposure one keyword argument away.
        The citizen writes the full number onto the printed form themselves.
        """
        from pdf_generator import _mask_aadhaar
        assert _mask_aadhaar("123456789012", full=True) == "XXXX XXXX 9012"
        assert _mask_aadhaar("123456789012", full=False) == "XXXX XXXX 9012"

    def test_generate_pdf_with_draft_false_no_watermark(self):
        """Generating with is_draft=False should produce a valid PDF."""
        from pdf_generator import generate_real_filled_form_pdf

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            generate_real_filled_form_pdf(
                filled_fields={"name": "Test User"},
                scheme_name="Test Scheme",
                form_fields=[{"fieldName": "name", "profileKey": "name", "labelEnglish": "Name",
                              "labelHindi": "naam", "type": "text", "required": True, "section": "Details"}],
                sections=[{"name": "Details", "nameHindi": "vivaran"}],
                output_path=out_path,
                is_draft=False,
            )
            assert os.path.exists(out_path)
            assert os.path.getsize(out_path) > 0
        finally:
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_generate_pdf_with_draft_true(self):
        """Generating with is_draft=True should produce a valid PDF."""
        from pdf_generator import generate_real_filled_form_pdf

        out_path = tempfile.mktemp(suffix=".pdf")
        try:
            generate_real_filled_form_pdf(
                filled_fields={"name": "Test User"},
                scheme_name="Test Scheme",
                form_fields=[{"fieldName": "name", "profileKey": "name", "labelEnglish": "Name",
                              "labelHindi": "naam", "type": "text", "required": True, "section": "Details"}],
                sections=[{"name": "Details", "nameHindi": "vivaran"}],
                output_path=out_path,
                is_draft=True,
            )
            assert os.path.exists(out_path)
            assert os.path.getsize(out_path) > 0
        finally:
            if os.path.exists(out_path):
                os.unlink(out_path)

    def test_format_field_value_empty(self):
        from pdf_generator import _format_field_value
        assert _format_field_value(None) == "_______________"
        assert _format_field_value("") == "_______________"

    def test_format_field_value_date(self):
        from pdf_generator import _format_field_value
        assert _format_field_value("1990-05-15", "date") == "15/05/1990"

    def test_format_field_value_phone(self):
        from pdf_generator import _format_field_value
        result = _format_field_value("9876543210", "phone")
        assert "98765" in result


# ─── Placing values on a real printed form ───

class TestLabelMatching:
    """Government forms print their own words, not the app's.

    The catalog calls a field "Full Name (as per Aadhaar)". The Haryana sports
    scholarship form calls it "Name of the Applicant". Matching only on the
    catalog label left the single most important field on the page blank.
    """

    def test_the_form_s_own_phrasing_is_recognised(self):
        from pdf_filler import FIELD_ALIASES

        assert "name of the applicant" in FIELD_ALIASES["name"]
        assert "bank's name" in FIELD_ALIASES["bank_name"]
        assert "aadhar no" in FIELD_ALIASES["aadhaar_number"], \
            "forms spell it Aadhar as often as Aadhaar"

    def test_relations_are_listed_before_the_bare_name(self):
        """"father's name" and "name" both match "Father's Name:". Resolving to
        the shorter one writes the applicant's own name onto their father's
        line, which is worse than leaving it blank."""
        from pdf_filler import _alias_hit

        hit = _alias_hit("4. father's name:", "father_husband_name", ())
        assert hit == "father's name"

    def test_search_handles_the_apostrophes_a_scan_produces(self):
        """OCR emits a typographic apostrophe, so a literal search finds
        nothing on a page that plainly reads Mother's Name."""
        from pdf_filler import _search_variants

        variants = _search_variants("mother's name")
        assert "mother’s name" in variants
        assert "mothers name" in variants


class TestProseIsRefused:
    """A label match inside a printed paragraph writes a value into the middle
    of a legal undertaking."""

    def test_a_declaration_sentence_is_not_a_label(self):
        from pdf_filler import _looks_like_a_label

        prose = ("Self-attested copy of my sports achievements, date of birth, "
                 "Bank Pass Book, Domicile Certificate have been enclosed.")
        assert not _looks_like_a_label(prose)

    @pytest.mark.parametrize("label", [
        "1. District:", "b) Sex: Male/Female", "Bank's Name:",
        "IFSC Code: --ll.", "9. Aadhar No:",
    ])
    def test_real_labels_are_accepted(self, label):
        """"IFSC Code: --ll." is a good label followed by scan noise. An
        earlier heuristic rejected anything ending in a full stop and threw it
        away."""
        from pdf_filler import _looks_like_a_label

        assert _looks_like_a_label(label)

    def test_a_long_line_is_not_a_label(self):
        from pdf_filler import _looks_like_a_label, MAX_LABEL_CHARS

        assert not _looks_like_a_label("x" * (MAX_LABEL_CHARS + 1))


class TestUnplacedIsReported:
    """A printed form rarely has a labelled box for every field the catalog
    knows. Saying which ones are missing is the difference between a citizen
    completing the form at home and finding out at the counter."""

    FIELDS = [
        {"profileKey": "name", "labelEnglish": "Full Name",
         "labelHindi": "पूरा नाम", "required": True},
        {"profileKey": "pincode", "labelEnglish": "PIN Code",
         "labelHindi": "पिन कोड", "required": True},
        {"profileKey": "branch_name", "labelEnglish": "Branch Name",
         "labelHindi": "शाखा", "required": False},
    ]

    def test_supplied_but_unplaceable_values_are_listed(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report(
            positions=[{"profileKey": "name"}],
            field_values={"name": "Priya", "pincode": "124507",
                          "branch_name": "Main"},
            form_fields=self.FIELDS,
        )
        keys = {r["profileKey"] for r in report}
        assert keys == {"pincode", "branch_name"}

    def test_the_report_says_which_ones_are_mandatory(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report(
            [], {"pincode": "124507", "branch_name": "Main"}, self.FIELDS)
        by_key = {r["profileKey"]: r for r in report}
        assert by_key["pincode"]["required"] is True
        assert by_key["branch_name"]["required"] is False

    def test_the_reason_is_bilingual(self):
        from pdf_filler import _unplaced_report

        report = _unplaced_report([], {"pincode": "124507"}, self.FIELDS)
        assert report[0]["reason"] and report[0]["reasonHindi"]
        assert report[0]["labelHindi"]

    def test_a_value_the_citizen_never_gave_is_not_reported(self):
        """They are not told to hand-write something they never supplied."""
        from pdf_filler import _unplaced_report

        # Only `name` was supplied, and it was placed. PIN code and branch are
        # unplaceable but blank, so there is nothing to warn about.
        assert _unplaced_report(
            [{"profileKey": "name"}], {"name": "Priya"}, self.FIELDS) == []

    def test_the_overlay_result_carries_the_shortfall(self):
        from pdf_filler import _unplaced_report
        import inspect
        import pdf_filler

        source = inspect.getsource(pdf_filler.fill_overlay_pdf)
        assert '"unplaced": _unplaced_report(' in source, \
            "a shortfall computed and not returned is a shortfall not reported"
        assert callable(_unplaced_report)
